log_level: info

processes:
  qdrant:
    command: qdrant
    availability:
      restart: on_failure
    ready_log_line: "Qdrant gRPC listening"

  ollama:
    command: ollama serve
    availability:
      restart: on_failure
    ready_log_line: "Listening on"

  ollama-init:
    command: |
      echo "Waiting for Ollama to be ready..."
      until curl -s http://localhost:11434/api/tags > /dev/null 2>&1; do
        sleep 1
      done
      echo "Ollama is ready, checking for nomic-embed-text model..."

      if ollama list | grep -q "nomic-embed-text"; then
        echo "Model nomic-embed-text already exists, skipping pull"
      else
        echo "Pulling nomic-embed-text model (this may take a few minutes on first run)..."
        ollama pull nomic-embed-text
        echo "Model pulled successfully!"
      fi
    depends_on:
      ollama:
        condition: process_started
    availability:
      restart: "no"
